/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import config.config;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Eljay
 */
public class processbrrw extends javax.swing.JFrame {

    /**
     
     */
    public processbrrw() {
        initComponents();
        getData();
    }
    
    void getData(){
        config con = new config();
        String sql = "SELECT * FROM tbl_books";
        con.displayData(sql, brrwtable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Brrw_table = new javax.swing.JScrollPane();
        brrwtable = new javax.swing.JTable();
        Username = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        book_id = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        borrow = new javax.swing.JPanel();
        Borrow = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brrwtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Brrw_table.setViewportView(brrwtable);

        getContentPane().add(Brrw_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 370, 280));

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 90, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        book_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        book_id.setForeground(new java.awt.Color(255, 255, 255));
        book_id.setText("Book Id:");
        getContentPane().add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("User name:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        borrow.setBackground(new java.awt.Color(30, 95, 95));
        borrow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borrow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Borrow.setForeground(new java.awt.Color(255, 255, 255));
        Borrow.setText("Borrow");
        Borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrowMouseClicked(evt);
            }
        });
        borrow.add(Borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        getContentPane().add(borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/bck.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 50));

        frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ima.jpg"))); // NOI18N
        getContentPane().add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void BorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrowMouseClicked
            
            String bookIdText = Id.getText().trim();
            String userName = Username.getText().trim();
            String userEmail = Email.getText().trim();

            if (bookIdText.isEmpty() || userName.isEmpty() || userEmail.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!");
                return;
            }

            int bookId;

            try {
                bookId = Integer.parseInt(bookIdText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Book ID must be a number!");
                return;
            }

            try {

                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection("jdbc:sqlite:my_data.db");

                // EXACT MATCH: 4 columns = 4 values
                String sql = "INSERT INTO tbl_borrower (U_name, U_email, status) VALUES (?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);


                pst.setString(1, userName);
                pst.setString(2, userEmail);
                pst.setString(3, "Borrowed");

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Borrow Successful!");

                Id.setText("");
                Username.setText("");
                Email.setText("");

                conn.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
                e.printStackTrace();
            }
    }//GEN-LAST:event_BorrowMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       brrw_bks bb = new brrw_bks();
       bb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(processbrrw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(processbrrw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(processbrrw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(processbrrw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new processbrrw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borrow;
    private javax.swing.JScrollPane Brrw_table;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel back;
    private javax.swing.JLabel book_id;
    private javax.swing.JPanel borrow;
    private javax.swing.JTable brrwtable;
    private javax.swing.JLabel email;
    private javax.swing.JLabel frame;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
