/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Main.login;
import config.Session;
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author Eljay
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        getData();
        
        if (!Session.isLoggedIn()) {
        JOptionPane.showMessageDialog(this, "You must login first!");
        login log = new login();
        log.setVisible(true);
        this.dispose();
        }
    }
    
    void getData(){
        config con = new config();
        String sql = "SELECT * FROM tbl_books";
        con.displayData(sql, book_table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearpub = new javax.swing.JTextField();
        Publisher = new javax.swing.JTextField();
        b_title = new javax.swing.JLabel();
        b_author = new javax.swing.JLabel();
        btable = new javax.swing.JScrollPane();
        book_table = new javax.swing.JTable();
        b_publsher = new javax.swing.JLabel();
        b_publish = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        addbks = new javax.swing.JLabel();
        booktitle = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(yearpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, -1));
        getContentPane().add(Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        b_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_title.setForeground(new java.awt.Color(255, 255, 255));
        b_title.setText("Book Title :");
        getContentPane().add(b_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        b_author.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_author.setForeground(new java.awt.Color(255, 255, 255));
        b_author.setText("Book Author :");
        getContentPane().add(b_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        book_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        btable.setViewportView(book_table);

        getContentPane().add(btable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 360, 280));

        b_publsher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_publsher.setForeground(new java.awt.Color(255, 255, 255));
        b_publsher.setText("Book Publisher :");
        getContentPane().add(b_publsher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        b_publish.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_publish.setForeground(new java.awt.Color(255, 255, 255));
        b_publish.setText("Book Publish :");
        getContentPane().add(b_publish, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        add.setBackground(new java.awt.Color(30, 95, 95));
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addbks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addbks.setForeground(new java.awt.Color(255, 255, 255));
        addbks.setText("Add books");
        addbks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbksMouseClicked(evt);
            }
        });
        add.add(addbks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 30));

        booktitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktitleActionPerformed(evt);
            }
        });
        getContentPane().add(booktitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/bck.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 50));

        Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ima.jpg"))); // NOI18N
        getContentPane().add(Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addbksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbksMouseClicked
     config con = new config();
     String sql = "INSERT INTO tbl_books (b_title, b_author, b_publisher, b_publish) VALUES (?, ?, ?, ?)";    
     con.addRecord(sql, booktitle.getText(), author.getText(), Publisher.getText(), yearpub.getText());
    }//GEN-LAST:event_addbksMouseClicked

    private void booktitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktitleActionPerformed
       
       
    }//GEN-LAST:event_booktitleActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       Admin ua = new Admin();
       ua.setVisible(true);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frame;
    private javax.swing.JTextField Publisher;
    private javax.swing.JPanel add;
    private javax.swing.JLabel addbks;
    private javax.swing.JTextField author;
    private javax.swing.JLabel b_author;
    private javax.swing.JLabel b_publish;
    private javax.swing.JLabel b_publsher;
    private javax.swing.JLabel b_title;
    private javax.swing.JLabel back;
    private javax.swing.JTable book_table;
    private javax.swing.JTextField booktitle;
    private javax.swing.JScrollPane btable;
    private javax.swing.JTextField yearpub;
    // End of variables declaration//GEN-END:variables
}
